services:
  stock-publisher:
    build: ./stock-publisher
    container_name: stock-publisher
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
      - TICKER_INTERVAL=1
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
