services:
  stock-publisher:
    build: ./stock-publisher
    container_name: stock-publisher
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
      - TICKER_INTERVAL=1
  stock-liveview:
    build: ./stock-liveview
    container_name: stock-liveview
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb1://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/?replicaSet=rs0
      - MONGODB_DB=stockmarket
      - MONGODB_COLLECTION=stocks
      - NODE_ENV=development
      - PORT=3000
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  mongodb1:
    image: mongo:7.0
    container_name: mongodb1
    ports:
      - "27017:27017"
    command: --replSet rs0 --bind_ip_all --port 27017
    volumes:
      - mongo1_data:/data/db
  mongodb2:
    image: mongo:7.0
    container_name: mongodb2
    ports:
      - "27018:27017"
    command: --replSet rs0 --bind_ip_all --port 27018
    volumes:
      - mongo2_data:/data/db
  mongodb3:
    image: mongo:7.0
    container_name: mongodb3
    ports:
      - "27019:27017"
    command: --replSet rs0 --bind_ip_all --port 27019
    volumes:
      - mongo3_data:/data/db

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
